### ISSUE TITLE
Property defaults is not allowed

### ISSUE THREAD

**Issue by ZebraFlesh** [Lona/vscode-github-actions#10]
<img width="431" alt="Screen Shot 2020-05-07 at 8 41 51 AM" src="https://user-images.githubusercontent.com/10542617/81301396-9cb98f00-903e-11ea-9302-8d82aad101df.png">

[ Pretty sure it's allowed](https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_iddefaultsrun)

edit: This is with version 3.0.0

**Comment by mathieudutour** [comment]
can you check your settings for `yaml.schemas`?

**Comment by ZebraFlesh** [comment]
I had these values in settings:
```
    "yaml.schemas": {
        "file:///Users/redacted/.vscode/extensions/me-dutour-mathieu.vscode-github-actions-2.2.7/schemas/workflow.schema.json": "/.github/workflows/*.yml",
        "file:///Users/redacted/.vscode/extensions/me-dutour-mathieu.vscode-github-actions-2.2.7/schemas/action.schema.json": "/action.yml"
    }
```

Deleting those values and some combination of updating/restarting the language server/vscode resolved it.

**Comment by mathieudutour** [comment]
yeah removing them should fix it
