### ISSUE TITLE
"Problems loading reference" error after updating to 3.0.0

### ISSUE THREAD

**Issue by wjrogers** [Lona/vscode-github-actions#11]
Each open workflow YAML file reports this error in the VS Code PROBLEMS tab:
> Problems loading reference 'file:///c%3A/Users/will/.vscode/extensions/me-dutour-mathieu.vscode-github-actions-2.2.7/schemas/workflow.schema.json': Unable to load schema from 'c:\Users\will\.vscode\extensions\me-dutour-mathieu.vscode-github-actions-2.2.7\schemas\workflow.schema.json': .

**Comment by mathieudutour** [comment]
delete the settings under `yaml.schemas`

**Comment by Bnaya** [comment]
Thanks!
The file location for me is:
`~/Library/Application Support/Code/User/settings.json`
