### ISSUE TITLE
Extension is not working

### ISSUE THREAD

**Issue by EndBug** [Lona/vscode-github-actions#14]
Hi! Every time I open a workflow file an error shows up:

> Problems loading reference 'file:///c%3A/Users/Federico%20Grandi/.vscode/extensions/me-dutour-mathieu.vscode-github-actions-2.2.7/schemas/workflow.schema.json': Unable to load schema from 'c:\Users\Federico Grandi\.vscode\extensions\me-dutour-mathieu.vscode-github-actions-2.2.7\schemas\workflow.schema.json': .

This is the complete error object:
```
{
	"resource": "/c:/EndBug/GitHub/r6api.js/.github/workflows/update.yml",
	"owner": "_generated_diagnostic_collection_name_#3",
	"code": "768",
	"severity": 8,
	"message": "Problems loading reference 'file:///c%3A/Users/Federico%20Grandi/.vscode/extensions/me-dutour-mathieu.vscode-github-actions-2.2.7/schemas/workflow.schema.json': Unable to load schema from 'c:\\Users\\Federico Grandi\\.vscode\\extensions\\me-dutour-mathieu.vscode-github-actions-2.2.7\\schemas\\workflow.schema.json': .",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 2
}
```

Is there any way to fix this?

**Comment by mathieudutour** [comment]
see https://github.com/Lona/vscode-github-actions/issues/11
