### ISSUE TITLE
Error without the extension installed

### ISSUE THREAD

**Issue by tapsboy** [Lona/vscode-github-actions#17]
I created this Issue on VSCode Yaml (https://github.com/redhat-developer/vscode-yaml/issues/338), but realized that the dependency is other way round

Despite disabling this extension, I get the error in GH action yml file, where it is trying to load the old version of the extension. 

![image](https://user-images.githubusercontent.com/868525/89108816-a5d1b680-d409-11ea-8511-fca05508e0c8.png)

Disabling both extensions solves the issue:

![image](https://user-images.githubusercontent.com/868525/89108856-1082f200-d40a-11ea-8212-e0e19ca079ed.png)

Would you have happen to have any ideas why?

**Comment by mathieudutour** [comment]
See #11
