### ISSUE TITLE
Workflow named deploy.yml pulling in unwanted schema

### ISSUE THREAD

**Issue by MetRonnie** [Lona/vscode-github-actions#21]
I have a GH Actions workflow named `deploy.yml` which is being validated against an unwanted schema.

See this reference to `schema.json` at the top of the file:

<img src="https://user-images.githubusercontent.com/61982285/113007233-f30b5100-916d-11eb-932b-bea7292eaddd.png" width="500"/>

And this erroneous flagged error:

![image](https://user-images.githubusercontent.com/61982285/113007105-d40cbf00-916d-11eb-8c18-42e513e38628.png)

> Property name is not allowed.
> yaml-schema: https://raw.githubusercontent.com/deployphp/deployer/master/src/schema.json

My `settings.json` does not contain any yaml schemas.

**Comment by mathieudutour** [comment]
yeah it'd because of https://github.com/SchemaStore/schemastore/pull/1356. Feel free to open an issue on this repo, not much I can do here
