### ISSUE TITLE
Error shows up on every workflow file.

### ISSUE THREAD

**Issue by EndBug** [Lona/vscode-github-actions#5]
I'm having some problems with the extension: it now shows this error every time I open a workflow file. 
I've already trie re-installing it but it did the exact same thing. IntelliSense still works fine though...

> Problems loading reference 'file:///c%3A/Users/fgran/.vscode/extensions/me-dutour-mathieu.vscode-github-actions-2.2.4/schemas/workflow.schema.json': Unable to load schema from 'c:\Users\fgran\.vscode\extensions\me-dutour-mathieu.vscode-github-actions-2.2.4\schemas\workflow.schema.json': .

**Comment by mathieudutour** [comment]
should be fixed in 2.2.7
