### ISSUE TITLE
Property continue-on-error is not allowed.

### ISSUE THREAD

**Issue by Bnaya** [Lona/vscode-github-actions#7]
Hey

First i really want to think about for this plugin!
Made my life with github actions much much much better!

For unclear reason for me, i'm getting a lint error on `continue-on-error: true` use
But on github the workflow jobs do run properly 

![Screen Shot 2020-04-25 at 18 05 46](https://user-images.githubusercontent.com/1304862/80283332-65cea980-871f-11ea-9583-63c06e0c283c.png)

**Comment by mathieudutour** [comment]
should be fixed with v3
