### ISSUE TITLE
Property 'outputs' is not allowed

### ISSUE THREAD

**Issue by KSXGitHub** [Lona/vscode-github-actions#9]
[documentation: jobs.<job_id>.output](https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjobs_idoutputs)

![screenshot](https://user-images.githubusercontent.com/11488886/80897818-1859ca00-8d27-11ea-9297-c58ac7fbc664.png)

**Comment by mathieudutour** [comment]
should be fixed with v3
